#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Write main.py — p4a requires this filename even when the real entry is elsewhere.
#
# Usage:
#   ./scripts/install_apk_main.sh DEST_DIR
#
# Environment:
#   APK_ENTRY   Python file to run (default: main_lvgl.py). Set to "skip" to leave main.py alone.
set -euo pipefail

DEST="${1:-}"
if [[ -z "$DEST" ]]; then
  echo "Usage: $0 DEST_DIR" >&2
  exit 1
fi

ENTRY="${APK_ENTRY:-main_lvgl.py}"
if [[ "$ENTRY" == "skip" ]]; then
  exit 0
fi

if [[ ! -f "$DEST/$ENTRY" ]]; then
  echo "APK entry not found: $DEST/$ENTRY" >&2
  exit 1
fi

cat > "$DEST/main.py" <<PY
# SPDX-License-Identifier: MIT
# p4a SDL2 bootstrap requires a file named main.py (generated by install_apk_main.sh).
import runpy

runpy.run_path("${ENTRY}", run_name="__main__")
PY

echo "==> Wrote $DEST/main.py -> $ENTRY"
